baseURL = "https://peetzweg.github.io/clawdbot-trmnl/"
languageCode = "en-us"
title = "trmnl-cli"

staticDir = ["static", "assets"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
